services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
    ports:
      - "5432:5432"
  swisssystem.webapp:
    image: swisssystem.webapp
    build:
      context: .
      dockerfile: SwissSystem.WebApp/Dockerfile

